import gql from 'graphql-tag'

const createSO = gql`mutation StoreSalesOrder (
  $id: Int,
  $type: String,
  $store_id: String,
  $store_name: String,
  $store_address: String,
  $store_city: String,
  $store_province: String,
  $store_country: String,
  $store_contact: String,
  $customer_id: String,
  $customer_name: String,
  $customer_address: String,
  $customer_phone: String,
  $customer_email: String,
  $courier_name: String,
  $courier_service: String,
  $receiver_id: String, #pake customer id
  $receiver_name: String,
  $receiver_address: String,
  $receiver_phone: String,
  $receiver_email: String,
  $marketer_id: String,
  # $marketer_name: String,
  $date: String,
  # $no: String,
  $delivery_to: String,
  $delivery_date: String,
  $payment_method: String,
  $payment_terms: Int,
  $invoice_terms: String,
  $shipping_terms: String,
  $lines: [ISalesOrderLine]
) {
  StoreSalesOrder (
  id: $id,
  type: $type,
  store_id: $store_id,
  store_name: $store_name,
  store_address: $store_address,
  store_city: $store_city,
  store_province: $store_province,
  store_country: $store_country,
  store_contact: $store_contact,
  customer_id: $customer_id,
  customer_name: $customer_name,
  customer_address: $customer_address,
  customer_phone: $customer_phone,
  customer_email: $customer_email,
  courier_name: $courier_name,
  courier_service: $courier_service,
  receiver_id: $receiver_id, #pake customer id
  receiver_name: $receiver_name,
  receiver_address: $receiver_address,
  receiver_phone: $receiver_phone,
  receiver_email: $receiver_email,
  marketer_id: $marketer_id,
  # $marketer_name: String,
  date: $date,
  # no: String,
  delivery_to: $delivery_to,
  delivery_date: $delivery_date,
  payment_method: $payment_method,
  payment_terms: $payment_terms,
  invoice_terms: $invoice_terms,
  shipping_terms: $shipping_terms,
  lines: $lines
  ) {
    id,
    no,
    date,
    type,
    store_id,
    store_name,
    store_address,
    store_city,
    store_province,
    store_country,
    store_contact,
    customer_id,
    customer_name,
    customer_address,
    customer_phone,
    customer_email,
    receiver_id,
    receiver_name,
    receiver_address,
    receiver_phone,
    receiver_email,
    courier_name,
    courier_service,
    delivery_to,
    delivery_date,
    payment_method,
    payment_terms,
    invoice_terms,
    shipping_terms,
    note,
    status,
    lines {
      product_name,
      qty,
      price,
      discount,
      additional_discount
    },
    # ref {
    #   DocumentType {
    #     DeliveryOrder {
    #       no,
    #       ref_type,
    #       ref_id,
    #       warehouse_id,
    #       warehouse_name,
    #       warehouse_note,
    #       receiver_type,
    #       receiver_id,
    #       receiver_name,
    #       receiver_note,
    #       shipper,
    #       shipper_ref_no,
    #       date,
    #       note,
    #       status
    #     }
    #   }
    # }
  }
}`

export default createSO
